#!/usr/bin/env python3
# from typing import *



# def solve(n: int, a: List[int]) -> int:
def solve(n, a):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    # failed to analyze input format
    a = int(input())  # TODO: edit here
    b, c = map(int, input().split())
    t = input()
    print(f'{a+b+c} {t}')

if __name__ == '__main__':
    main()
